# Generated by Django 3.0.5 on 2020-10-14 12:21

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=255)),
                ('post_description', models.TextField()),
                ('comment', djongo.models.fields.JSONField()),
                ('tags', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Prueba1',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('dias', djongo.models.fields.JSONField()),
                ('casos', djongo.models.fields.JSONField()),
            ],
        ),
    ]
