# Generated by Django 3.0 on 2020-11-17 21:02

from django.db import migrations, models
import djongo.models.fields
import mongoconnect.models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoconnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('profesionales_que_atendieron', djongo.models.fields.JSONField()),
                ('sesiones_medica', djongo.models.fields.ArrayField(blank=True, default=list, model_container=mongoconnect.models.Sesiones_medica)),
            ],
        ),
    ]
